### PR TITLE
Make it possible to switch songs by swiping in the currently playing view

### PR DESCRIPTION
**Pull request by FriederHannenheim**

### CODE REVIEW

**Comment by FriederHannenheim** [comment]
Maybe we should introduce a threshold so accidental swipes don't do anything

**Comment by moritz-weber** [comment]
Thanks for the pull request. Yeah, I thought about these gestures as well. I think, a threshold could be a good idea. I'll test it in the next days. I often feel that having gestures in all 4 directions can become quite cumbersome to use (because of accidental swipes in any direction), but maybe we find a satisfying solution.

**Comment by moritz-weber** [comment]
I just applied the changes locally and tested them. There wasn't really an issue with accidental swipes (though I only tested it for a couple of minutes). I'll continue using the changes in my personal build.

However, I expected the swipes to result in the opposite action (left-to-right: next song). I think, both directions have their arguments for them. To clarify this for the user, animations would be needed to indicate the song change. In Spotify, it is made clear because I see the album cover moving.

If you want to continue working on this, feel free to extend the pull request. Otherwise, I'd create an issue for this.

**Comment by FriederHannenheim** [comment]
Hmm. I only picked up flutter yesterday and this PR is the first thing I coded. Implementing swipe animations looks like an interesting challenge though. I will look into how this could be done and implement it if I'm able to.

**Comment by FriederHannenheim** [comment]
@moritz-weber I implemented an animation for swiping. Please test it to see if you like it. Another approach we could use would be to remove the AnimatedSwitcher and just set the next and previous AlbumArt as background to the Dismissible. Though we would need special handling for if the user changes the queue then.

**Comment by moritz-weber** [comment]
Thanks @FriederHannenheim, I attached a screen recording for you to check if the animation is the same as on your phone.
I think, Dismissible is not the right way to go here. Usually, it is used to remove an element from a list, which is not the case here. Thus, it creates this kind of weird animation after being swiped away (I think).

The last swipe of the video changes the cover, but not the song. This is because `skipToPrevious` actually just skips back to 0 of the same song after 5 seconds or so have passed. I'll clarify the interface here, so nothing for you to worry about.

I had a look at the available Flutter widgets and think that [PageView](https://api.flutter.dev/flutter/widgets/PageView-class.html) is the way to go. With `PageView.builder`, we could just create a list of `AlbumArt` on demand. Or maybe even better, include the song title and album/artist info in this 'page' to have a larger area that can be swiped.

https://user-images.githubusercontent.com/17176771/211211188-d002c184-8034-4db6-a4fa-35fb46c1dcbc.mp4

**Comment by moritz-weber** [comment]
Small addition: 
If you want to build a release build and get an error, just change line 80 in src/android/app/build.gradle to:

    signingConfig signingConfigs.debug

Also, I set my line width for Dart to 100 characters, as I don't see a compelling argument for 80. If you use the same width, we avoid formatting changes.

**Comment by FriederHannenheim** [comment]
@moritz-weber I implemented the swiping with PageView. But for some reason the queue index doesn't update when the Observer Updates so if you skip songs manually the album image doesn't update. Do you know why this is the case?

**Comment by moritz-weber** [comment]
That looks really good so far. If it's ok with you, I'll just merge this and tinker around with it myself a little bit.
As you can see in `currently_playing.dart`, I'm not quite happy with the "giant" Observer anyway and might change some stuff there.

I'm not always sure under which circumstances Observer triggers a rebuild - and this is one of those cases.
My best guess is that `queueIndex` is not used directly (you can access it in the State as `widget.queueIndex`) and it's not directly used for widget creation. So maybe the Observer thinks that the widget is still valid and doesn't need to be rebuilt.

**Pull request merged**
