### PR TITLE
Add opus to default allowed file extensions

### PR DESCRIPTION
**Pull request by FriederHannenheim**

### CODE REVIEW

**Comment by moritz-weber** [comment]
Is opus playback working for you? There is currently an open issue to support it, so I thought it wouldn't make sense to include it in the defaults.

**Comment by FriederHannenheim** [comment]
It's working fine for me. The Tags are also read and displayed correctly

**Comment by FriederHannenheim** [comment]
Android supports opus since Android 5. IOS doesn't support it that's why there's an issue in just_audio I think.

**Comment by moritz-weber** [comment]
Ok, I just tested it on my phone. You're right. The only issue I had with files converted from FLAC was the missing year tag.

Thanks for your help :)

**Pull request merged**
